### ISSUE TITLE
error in vue2 with typescript

### ISSUE THREAD

**Issue by alfredcc** [vueuse/sound#14]
Thank you to share this amazing project. But I got some problems with setup on my vue2 project.

ERROR in /Users/---/Developer/**/node_modules/@vueuse/sound/dist/esm/src/types.d.ts
1:35 Could not find a declaration file for module 'howler'. '/Users/---/Developer/---/node_modules/howler/dist/howler.js' implicitly has an 'any' type.
  Try `npm install @types/howler` if it exists or add a new declaration (.d.ts) file containing `declare module 'howler';`
  > 1 | import { Howl, HowlOptions } from 'howler';
      |                                   ^
    2 | import { ComputedRef, Ref } from 'vue-demi';
    3 | export interface HowlStatic {
    4 |     new (properties: HowlOptions): Howl;
No lint errors found

**Comment by alfredcc** [comment]
try `declare module "howler"; ` in shims-vue.d.ts

**Comment by alfredcc** [comment]
also tried to clean up all node_modules

**Comment by alfredcc** [comment]
npm install @types/howler 
not work too.

**Comment by alfredcc** [comment]
find this https://github.com/joshwcomeau/use-sound/issues/20

**Comment by Tahul** [comment]
Hey, could you let me know if your issue has been fixed by v2?

Thanks a lot 🙏
