### ISSUE TITLE
Playing Multiple Sounds

### ISSUE THREAD

**Issue by ismaildkc** [vueuse/sound#16]
How can i use multiple sound source without using sprites?
Different buttons can be play different sounds

**Comment by Tahul** [comment]
I think you can call `useSound` multiple times?

```
const { play } = useSound('/my-sound-1.mp3')
const { play: playSecond } = useSound('/my-sound-2.mp3')
```

Let me know if this doesn't solve your issue! 🙏

**Comment by caudurodev** [comment]
Is there not way to provide a dynamic path to a local or remote file?

I'm also looking for this as I have thousands of sound files and want to only load the necessary one.
