### ISSUE TITLE
Doesn't work in production mode

### ISSUE THREAD

**Issue by afifrizqiawan** [vueuse/sound#9]
I'm using this lib and work perfectly in local development mode, but when i deployed to netlify the sound doesn't work with no error. Does anybody have the same issue?

**Comment by Tahul** [comment]
Hello @afifrizqiawan ;

Could you provide more details about your implementation ?

As you can see on https://vue-use-sound.netlify.app, this app works perfectly fine in production mode.

There might be something wrong on your side that we could investigate with your code.

**Comment by Tahul** [comment]
Hello @afifrizqiawan,

As there is no answer from your side, I guess you found how to fix your issue.

I'll close this one for now, if you encounter any other problem with this package, open another one or re-open this one to your will. :)

**Comment by hamotskyi** [comment]
Hi

**Comment by hamotskyi** [comment]
Hi 
I'm novice developer. After "npm run serve" it's work perfectly. But after "npm run build", there is no sound at all.

**Comment by kjolibois** [comment]
I'm also having this problem, it keeps saying Cannot read property 'play' of undefined

**Comment by laurentvizir** [comment]
For Nuxt 2 users out there : I was having the same kind of issue. After a bit of research and some trial/error, I found out that [@nuxtjs/composition-api package]( https://composition-api.nuxtjs.org/getting-started/setup) needed to be installed and configured to have this module work in production.

**Comment by nalini06** [comment]
Heyy @laurentvizir will that work for node js application also, currently i using 'say' package for text to speech, its working fine, I getting audio output in local, but I deployed in aws ubuntu ec2 instace, then im not able to hear the sound

**Comment by laurentvizir** [comment]
Hi @nalini06 ! It's been a while (almost a year) since I've faced the issue and posted my comment... so I do not remember anything about it :laughing: ...hence I cannot give you more guidance. Sorry and I hope you'll find the fix to your issue.
